app:
  baseUrl: https://backstage-k8s.maksonlee.com

backend:
  baseUrl: https://backstage-k8s.maksonlee.com
  listen: ':7007'
  cors:
    origin: https://backstage-k8s.maksonlee.com
    credentials: true
