apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-k8s-reader
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-k8s-readonly
rules:
  - apiGroups: ['', 'apps', 'batch', 'autoscaling', 'networking.k8s.io']
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
      - jobs
      - cronjobs
      - horizontalpodautoscalers
      - ingresses
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['metrics.k8s.io']
    resources: ['pods']
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-k8s-readonly
subjects:
  - kind: ServiceAccount
    name: backstage-k8s-reader
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: backstage-k8s-readonly
  apiGroup: rbac.authorization.k8s.io
