apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backstage
  namespace: observability
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - backstage
  selector:
    matchLabels:
      app: homelab-backstage
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
